DROP TABLE Users CASCADE;
DROP TABLE Project CASCADE;
DROP TABLE Bug CASCADE;
DROP TABLE Invited CASCADE;
DROP TABLE Log CASCADE;
DROP TABLE Notified CASCADE;
DROP TABLE Participant CASCADE;
DROP TABLE Assigned CASCADE;